<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>roughcut</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RoughCut.Media/RoughCut.Media.csproj" />
    <ProjectReference Include="../RoughCut.Application/RoughCut.Application.csproj" />
  </ItemGroup>
</Project>
