<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>roughcut-desktop</AssemblyName>
    <RestoreAdditionalProjectSources>$(MSBuildThisFileDirectory)..\..\vendor\nuget</RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RoughCut.Application/RoughCut.Application.csproj" />
    <PackageReference Include="CupriFace" Version="0.26.1" />
    <PackageReference Include="CupriFace.Shell" Version="0.26.1" />
  </ItemGroup>
</Project>
